version: "3.8"

services:
  jaeger-tracing-java-service:
    container_name: jaeger-tracing-java-service
    build: 
      context: "./jaeger-tracing-java-service"
      # dockerfile: Dockerfile-alternate
    ports: 
      - "8080:8080"

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.9
    container_name: jaeger-tracing
    ports:
      - "16686:16686"
      - "6831:6831/udp"